#!/bin/bash

source dialog_utils.sh

lib_test() {
	function_id=$1; shift
	function_exec=$1; shift

	case "$function_id" in
		"gauge")
			simular_processo_longo | $function_exec $@	
			;;
		"mixedgauge")
			mgauge_task_queue=(
				"simular_processo_longo 0.5 5"	
				"simular_processo_longo 1 2"
				"simular_processo_longo 0.5 3"
				"simular_processo_longo 2 9"
			)
			mgauge_task_id=(
				"Task 1"
				"Task 2"
				"Task 3"
				"Task 4"
			)

			$function_exec $@
			;;
		*)
			$function_exec $@
			;;
	esac	

	echo "${function_id}[$DIALOG_RETURN]: [$DIALOG_ANSWER]" >> tracing.log

	clear
}

simular_processo_longo() {
	time_sleep=${1-1}
	status_return=${2-0}
    
	# Simulação de um processo longo
    for i in {1..10}; do
        sleep $time_sleep
        echo $((i * 10))
    done

	return $status_return
}

> tracing.log

declare -A test_execs=(
	[yesno]='lib_test yesno dialog_yesno'
	[buildlist]='lib_test buildlist dialog_buildlist'
	[calendar]='lib_test calendar dialog_calendar'
	[checklist]='lib_test checklist dialog_checklist'
	[dselect]='lib_test dselect dialog_dselect'
	[editbox]='lib_test editbox dialog_editbox'
	[form]='lib_test form dialog_form'
	[fselect]='lib_test fselect dialog_fselect'
	[gauge]='lib_test gauge dialog_gauge'
	[infobox]='lib_test infobox dialog_infobox'
	[inputbox]='lib_test inputbox dialog_inputbox'
	[inputmenu]='lib_test inputmenu dialog_inputmenu'
	[menu]='lib_test menu dialog_menu'
	[mixedform]='lib_test mixedform dialog_mixedform'
	[mixedgauge]='lib_test mixedgauge dialog_mixedgauge'
	[msgbox]='lib_test msgox dialog_msgbox'
	[passwordbox]='lib_test passwordbox dialog_passwordbox'
)

exec_cmd=$1; shift

if [ -z "$exec_cmd" ]; then
	for id in "${!test_execs[@]}"; do
		${test_execs[$id]}
	done
else
	case "$exec_cmd" in
		"--help")
			echo "Dialog interface utils use example:"
			echo "Usage: $0 [ command [ ...args ] ]"
			echo "Box options parameters:"
  			echo -e "\tyesno        <text> <height> <width>"
  			echo -e "\tbuildlist    <text> <height> <width> <list-height> <tag1> <item1> <status1>..."
  			echo -e "\tcalendar     <text> <height> <width> <day> <month> <year>"
  			echo -e "\tchecklist    <text> <height> <width> <list height> <tag1> <item1> <status1>..."
  			echo -e "\tdselect      <directory> <height> <width>"
  			echo -e "\teditbox      <file> <height> <width>"
  			echo -e "\tform         <text> <height> <width> <form height> <label1> <l_y1> <l_x1> <item1> <i_y1> <i_x1> <flen1> <ilen1>..."
  			echo -e "\tfselect      <filepath> <height> <width>"
  			echo -e "\tgauge        <text> <height> <width> [<percent>]"
  			echo -e "\tinfobox      <text> <height> <width>"
  			echo -e "\tinputbox     <text> <height> <width> [<init>]"
  			echo -e "\tinputmenu    <text> <height> <width> <menu height> <tag1> <item1>..."
  			echo -e "\tmenu         <text> <height> <width> <menu height> <tag1> <item1>..."
  			echo -e "\tmixedform    <text> <height> <width> <form height> <label1> <l_y1> <l_x1> <item1> <i_y1> <i_x1> <flen1> <ilen1> <itype>..."
  			echo -e "\tmixedgauge   <text> <height> <width> <percent> <tag1> <item1>..."
  			echo -e "\tmsgbox       <text> <height> <width>"
  			echo -e "\tpasswordbox  <text> <height> <width> [<init>]"
  			#echo -e "\t--passwordform <text> <height> <width> <form height> <label1> <l_y1> <l_x1> <item1> <i_y1> <i_x1> <flen1> <ilen1>..."
  			#echo -e "\t--pause        <text> <height> <width> <seconds>"
  			#echo -e "\t--prgbox       <text> <command> <height> <width>"
  			#echo -e "\t--programbox   <text> <height> <width>"
  			#echo -e "\t--progressbox  <text> <height> <width>"
  			#echo -e "\t--radiolist    <text> <height> <width> <list height> <tag1> <item1> <status1>..."
  			#echo -e "\t--rangebox     <text> <height> <width> <min-value> <max-value> <default-value>"
  			#echo -e "\t--tailbox      <file> <height> <width>"
  			#echo -e "\t--tailboxbg    <file> <height> <width>"
  			#echo -e "\t--textbox      <file> <height> <width>"
  			#echo -e "\t--timebox      <text> <height> <width> <hour> <minute> <second>"
  			#echo -e "\t--treeview     <text> <height> <width> <list-height> <tag1> <item1> <status1> <depth1>..."
			;;
		"--version")
			echo "Dialog interface use example 1.0"
			echo "Author: Thiago F. dos S. (Thino Tsukimichi)"
			echo "Copyright (C) 2024 Free Software Foundation, Inc."
			echo "This is free software; see the source for copying conditions.  There is NO"
			echo "warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
			;;
		*)
			${test_execs[$exec_cmd]} $@
			;;
	esac
fi
